# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dbProjName : ''
  armTemplateFolder : 'yayak.db.template'

stages:
- stage: 'Build'
  displayName: 'Build The Application'
  jobs:
    - job: 'Copy_ARM_Template'
      displayName: 'Copy ARM Template'
      pool:
       vmImage: ubuntu-latest
      steps:
        - task : CopyFiles@2
          inputs:
            SourceFolder: '$(armTemplateFolder)/'
            Contents: 'azuredeploy*.json'
            TargetFolder: '$(Build.artifactStagingDirectory)/ARM'
        - task: PublishBuildArtifacts@1
          inputs:
           pathToPublish: $(Build.ArtifactStagingDirectory)
           publishLocation: 'Container'

- stage: 'Dev'
  displayName: 'Deploy to Dev'
  variables:
    - group: 'DEV'
  jobs: 
   - deployment: 
     pool:
       vmImage: 'windows-2019'
     environment: 'Dev'
     strategy:
        runOnce:
          deploy:
           steps:
              - download: current
                artifact: drop
              - task: replacetokens@5
                inputs:
                  rootDirectory: '$(Pipeline.Workspace)/drop/ARM'
                  targetFiles: 'azuredeploy.parameters.$(env).json'
                  encoding: 'auto'
                  tokenPattern: 'custom'
                  tokenPrefix: '#'
                  tokenSuffix: '#'
                  writeBOM: true
                  actionOnMissing: 'warn'
                  keepToken: false
                  actionOnNoFiles: 'continue'
                  enableTransforms: false
                  enableRecursion: false
                  useLegacyPattern: false
                  enableTelemetry: true
              - task: AzureResourceManagerTemplateDeployment@3
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: 'Azure subscription 1(07dbce66-6476-4471-a7ce-a2ff48fe684b)'
                  subscriptionId: '07dbce66-6476-4471-a7ce-a2ff48fe684b'
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '$(arm_ResourceGroupName)'
                  location: 'Southeast Asia'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(Pipeline.Workspace)/drop/ARM/azuredeploy.json'
                  csmParametersFile: '$(Pipeline.Workspace)/drop/ARM/azuredeploy.parameters.dev.json'
                  deploymentMode: 'Incremental'
                  
              